---
version: "1.0.0"

namespace: "local"
name: "system"
description: "Ansible collection for Linux system roles, playbooks and plugins."

authors:
  - "Alex Muir"

readme: "README.md"
license_file: "LICENSE"

repository: "https://github.com/alexmuir97/ansible-collection-local.system"
documentation: "https://github.com/alexmuir97/ansible-collection-local.system"
homepage: "https://github.com/alexmuir97/ansible-collection-local.system"
issues: "https://github.com/alexmuir97/ansible-collection-local.system/issues"

tags:
  - "linux"
  - "infrastructure"
  - "networking"
  - "security"
  - "storage"
  - "tools"

dependencies: {}

build_ignore: []
