---
- name: "Install sshd dnf packages"
  become: true
  ansible.builtin.dnf:
    name: "{{ sshd_package_name }}"
    state: "present"
  notify: "Restart sshd systemd services"

- name: "Provide sshd configuration file"
  become: true
  ansible.builtin.template:
    src: "{{ item }}.conf.j2"
    dest: "/etc/ssh/sshd_config.d/60-{{ item }}.conf"
    owner: "root"
    group: "root"
    mode: "0644"
    validate: "/usr/sbin/sshd -t -f %s"
  loop:
    - "authentication"
    - "connection"
    - "logging"
    - "session"
  notify: "Restart sshd systemd services"

- name: "Manage sshd systemd services"
  become: true
  ansible.builtin.systemd:
    name: "{{ sshd_service_name }}"
    state: "{{ sshd_service_state }}"
    enabled: "{{ sshd_service_enabled }}"

- name: "Manage sshd seinux port"
  become: true
  community.general.seport:
    ports: "{{ sshd_config_port | default(22) }}"
    proto: "tcp"
    setype: "ssh_port_t"
    state: "present"
  when: "ansible_selinux.status == 'enabled'"

- name: "Get service facts"
  ansible.builtin.service_facts:

- name: "Manage sshd firewalld policy"
  become: true
  ansible.posix.firewalld:
    service: "{{ sshd_firewall_service }}"
    state: "{{ sshd_firewall_state }}"
    zone: "{{ sshd_firewall_zone | default(omit) }}"
    immediate: "{{ sshd_firewall_immediate }}"
    permanent: "{{ sshd_firewall_permanent }}"
  when:
    - "ansible_facts.services['firewalld.service'] is defined"
    - "ansible_facts.services['firewalld.service']['state'] == 'running'"
    - "sshd_config_port is not defined"

- name: "Manage sshd firewalld policy (custom port)"
  become: true
  ansible.posix.firewalld:
    port: "{{ sshd_config_port }}/tcp"
    state: "{{ sshd_firewall_state }}"
    zone: "{{ sshd_firewall_zone | default(omit) }}"
    immediate: "{{ sshd_firewall_immediate }}"
    permanent: "{{ sshd_firewall_permanent }}"
  when:
    - "ansible_facts.services['firewalld.service'] is defined"
    - "ansible_facts.services['firewalld.service']['state'] == 'running'"
    - "sshd_config_port is defined"
